import { BookOpen, Check, Flag, LockKeyhole, Quote, ShieldCheck } from 'lucide-react';
import { Link } from 'wouter';
import { SectionKicker } from '@/components/site-shell';

export default function About() {
  return (
    <div className="mx-auto max-w-[1280px] px-5 pb-20 pt-12 lg:px-8 lg:pt-16">
      <header className="grid gap-10 border-b border-border pb-14 lg:grid-cols-[1.15fr_.85fr]"><div><SectionKicker>Редакционная карта</SectionKicker><h1 className="mt-5 max-w-4xl font-display text-[clamp(4.5rem,11vw,9rem)] font-semibold leading-[.78] tracking-tight">О<br /><span className="text-primary">ПРОЕКТЕ</span></h1></div><div className="flex items-end"><p className="max-w-md text-lg leading-8 text-muted-foreground">«Арсенал» — русскоязычная энциклопедия, которая рассматривает оружие как исторический и технологический объект, а не как инструкцию или символ статуса.</p></div></header>
      <section className="grid gap-12 py-16 lg:grid-cols-[.65fr_1.35fr]"><div><div className="sticky top-28"><div className="font-meta text-[10px] uppercase tracking-[.16em] text-primary">Наше обещание</div><div className="mt-5 font-display text-4xl leading-[.88]">Факт важнее эффекта.<br />Контекст важнее мифа.</div></div></div><div className="space-y-7 text-base leading-8 text-foreground/80"><p>Мы собираем карточки моделей, чтобы обычному читателю было проще разобраться в названиях, периодах, производителях и взаимосвязях. Каждая запись объясняет базовые понятия человеческим языком и показывает, где заканчивается достоверный факт и начинается легенда.</p><p>Мы не соревнуемся в детализации ради детализации. Устройство описывается на высоком уровне — ровно настолько, чтобы понять принцип и историческую роль. Сведения, которые могут превратить справку в руководство, намеренно остаются за пределами проекта.</p><div className="camouflage mt-10 p-6 text-[hsl(var(--sidebar-foreground))]"><Quote size={22} className="text-[hsl(var(--sidebar-primary))]" /><p className="mt-5 max-w-2xl font-display text-3xl leading-[.95]">Хорошая энциклопедия не делает предмет опаснее. Она делает разговор о нём точнее.</p></div></div></section>
      <section className="border-y border-border py-14"><SectionKicker>Принципы отбора</SectionKicker><div className="mt-8 grid gap-px overflow-hidden border border-border bg-border md:grid-cols-2">{[['01', 'Проверяемость', 'Опираемся на музейные каталоги, архивы, профильные издания и первичные документы. Ссылки ведут к внешним материалам, когда это возможно.'], ['02', 'Нейтральный язык', 'Не романтизируем, не демонизируем и не подменяем историю рекламными формулировками.'], ['03', 'Читательский масштаб', 'Объясняем термины и связи без предположения, что читатель уже знаком с предметом.'], ['04', 'Безопасная граница', 'Не публикуем пошаговые сведения о сборке, разборке, изготовлении, модификации или использовании оружия.']].map(([number, title, text]) => <div key={number} className="bg-card p-6 sm:p-8"><div className="font-meta text-[10px] text-primary">{number}</div><h2 className="mt-7 font-display text-3xl">{title}</h2><p className="mt-3 text-sm leading-7 text-muted-foreground">{text}</p></div>)}</div></section>
      <section className="py-16"><div className="grid gap-8 md:grid-cols-3"><Principle icon={<BookOpen size={19} />} title="Что внутри" text="Модель, семейство, даты, происхождение, высокоуровневый принцип и связи с вариантами." /><Principle icon={<LockKeyhole size={19} />} title="Чего нет" text="Инструкций, чертежей для изготовления, советов по переделке и практических сценариев применения." /><Principle icon={<Flag size={19} />} title="Для кого" text="Для читателей, исследователей, преподавателей и всех, кто хочет разобраться в истории предмета." /></div></section>
      <section className="border-t border-border pt-10"><div className="flex flex-col items-start justify-between gap-5 sm:flex-row sm:items-center"><div><div className="font-meta text-[10px] uppercase tracking-[.14em] text-primary">Готовы начать</div><p className="mt-2 text-sm text-muted-foreground">Откройте карточку и читайте в своём темпе.</p></div><Link href="/catalog" data-testid="link-about-catalog" className="inline-flex items-center gap-3 bg-primary px-5 py-3 font-meta text-[10px] uppercase tracking-[.14em] text-primary-foreground">Перейти в каталог <Check size={15} /></Link></div></section>
    </div>
  );
}

function Principle({ icon, title, text }: { icon: React.ReactNode; title: string; text: string }) {
  return <div className="border-t-2 border-primary pt-5"><div className="text-primary">{icon}</div><h2 className="mt-5 font-display text-3xl">{title}</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">{text}</p></div>;
}